### ISSUE TITLE
Tests gets executed even if the ubports.no_tests file is present

### ISSUE THREAD

**Issue by mardy** [ubports/build-tools#11]
This is a strange issue which affects only the amd64 builds: it looks like the `build-binary.sh` script properly sets the `DEB_BUILD_OPTIONS` variable, but then for some reason it's ignored during the amd64 build.

Builds for armhf and arm64 appear to handle it correctly. See for example: https://ci.ubports.com/blue/organizations/jenkins/qtcontacts-sqlite/detail/xenial_-_mercontacts/6/pipeline/25

Looking at the logs, I suspect that a different shell might be used.

**Comment by mardy** [comment]
I think I finally found the issue: the [build-and-provide-package](https://github.com/mika/jenkins-debian-glue/blob/master/scripts/build-and-provide-package) script invokes `cowbuilder` with `sudo`. That causes the environment to be cleaned, so out `DEB_BUILD_OPTIONS` variable is ignored. The reason why it works in the `armhf` and `arm64` builders is that in them Jenkins is running as the root user, so `sudo` is a no-op (while in the `amd64` builder, Jenkins is running as `jenkins`).

Possible fixes (from best to worst):

1) Replace the calls to sudo with `sudo DEB_BUILD_OPTIONS="$DEB_BUILD_OPTIONS <command>"`; make sure you replace *all* the invocations, are there are several ones.
2) Like the above, but replace the calls to sudo with `sudo -E`, which preserves the whole environment.
3) Reconfigure the amd64 node to run Jenkins as the root user

**Comment by mariogrip** [comment]
Fixed by adding `Defaults  env_keep+="DEB_*"` sudoers
