### ISSUE TITLE
Add missing core apps to Openstore?

### ISSUE THREAD

**Issue by Flohack74** [ubports/build-tools#4]
See http://ci.ubports.com/blue/organizations/jenkins/click-import/detail/click-import/86/pipeline - Does it mean we don´t have the missing ones in the store yet?

**Comment by mariogrip** [comment]
Yes, that check the store for those apps.here is the list of app id's it checks for https://github.com/ubports/build-tools/blob/master/clicks.list

**Comment by dobey** [comment]
It seems also that there is some issue where the clicks which are pre-installed on devices, "did not come from the open store." I just recently flashed 15.04 back onto my nexus 4, and all the updates shown in the open store app had this warning with them.

**Comment by Flohack74** [comment]
And I cant get rid of a warning for clock app about "not from the openstore", but being higher in build no. We should make sure we push them there by time.

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/build-tools/pull/30
